source 'https://github.com/CocoaPods/Specs.git'

project 'ecommerce-afnetworking-objc'

target 'ecommerce-afnetworking-objc'
target 'ecommerce-afnetworking-objcTests'

pod 'AppDynamicsAgent'
pod 'AFNetworking', '~> 3.0'

platform :ios, '7.0'
